# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-09 12:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateofcreation', models.DateTimeField(blank=True, default=datetime.datetime(2017, 9, 9, 12, 12, 13, 312195), null=True)),
                ('createdby', models.CharField(blank=True, max_length=256, null=True)),
                ('source', models.CharField(blank=True, max_length=1000, null=True)),
                ('text', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
