# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-09 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='dateofcreation',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
