# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-09 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20170909_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
