# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-13 17:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_posts_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'permissions': (('can_mke_new_posts', 'Can make new posts'),)},
        ),
    ]
