# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svrea_etl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etlhistory',
            name='etldate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
