# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 13:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svrea_etl', '0002_etlhistory_etldate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etllistings',
            old_name='listing_area_max',
            new_name='listing_area_15',
        ),
        migrations.RenameField(
            model_name='etllistings',
            old_name='listing_area_min',
            new_name='listing_area_85',
        ),
        migrations.RenameField(
            model_name='etllistings',
            old_name='listing_rent_max',
            new_name='listing_rent_15',
        ),
        migrations.RenameField(
            model_name='etllistings',
            old_name='listing_rent_min',
            new_name='listing_rent_85',
        ),
    ]
