# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 13:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svrea_etl', '0003_auto_20170423_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etllistings',
            old_name='sold_area_max',
            new_name='sold_area_15',
        ),
        migrations.RenameField(
            model_name='etllistings',
            old_name='sold_area_min',
            new_name='sold_area_85',
        ),
        migrations.RenameField(
            model_name='etllistings',
            old_name='sold_rent_max',
            new_name='sold_rent_15',
        ),
        migrations.RenameField(
            model_name='etllistings',
            old_name='sold_rent_min',
            new_name='sold_rent_85',
        ),
    ]
