# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-12 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svrea_etl', '0004_auto_20170423_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtlListingsDaily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateTimeField(blank=True, null=True)),
                ('geographic_type', models.CharField(blank=True, max_length=50, null=True)),
                ('geographic_name', models.CharField(blank=True, max_length=50, null=True)),
                ('active_listings', models.IntegerField(blank=True, null=True)),
                ('sold_today', models.IntegerField(blank=True, null=True)),
                ('listing_price_avg', models.IntegerField(blank=True, null=True)),
                ('listing_price_med', models.IntegerField(blank=True, null=True)),
                ('listing_price_sqm_avg', models.IntegerField(blank=True, null=True)),
                ('listing_price_sqm_med', models.IntegerField(blank=True, null=True)),
                ('listing_area_avg', models.IntegerField(blank=True, null=True)),
                ('listing_area_med', models.IntegerField(blank=True, null=True)),
                ('listing_rent_avg', models.IntegerField(blank=True, null=True)),
                ('listing_rent_med', models.IntegerField(blank=True, null=True)),
                ('sold_price_avg', models.IntegerField(blank=True, null=True)),
                ('sold_price_med', models.IntegerField(blank=True, null=True)),
                ('sold_price_sqm_avg', models.IntegerField(blank=True, null=True)),
                ('sold_price_sqm_med', models.IntegerField(blank=True, null=True)),
                ('sold_area_avg', models.IntegerField(blank=True, null=True)),
                ('sold_area_med', models.IntegerField(blank=True, null=True)),
                ('sold_rent_avg', models.IntegerField(blank=True, null=True)),
                ('sold_rent_med', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='EtlListings',
        ),
    ]
