# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-31 17:36
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svrea_etl', '0007_etlhistory_etlperiod'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtlTimeSeriesFavouriteTimeSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationdate', models.DateTimeField(blank=True, null=True)),
                ('favouritename', models.CharField(blank=True, max_length=256, null=True)),
                ('username', models.CharField(blank=True, max_length=256, null=True)),
                ('usergroup', models.CharField(blank=True, max_length=256, null=True)),
                ('timeseriesdict', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
