# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-01 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svrea_etl', '0010_auto_20170731_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='etltimeseriesfavourite',
            name='flag',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
