# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-01 11:38
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svrea_etl', '0011_etltimeseriesfavourite_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etltimeseriesfavourite',
            name='timeseriesdict',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
