# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-01 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svrea_etl', '0012_auto_20170801_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='etltimeseriesfavourite',
            name='lastupdatedate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
