# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-04 08:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svrea_etl', '0013_etltimeseriesfavourite_lastupdatedate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EtlListingsQuaterly',
            new_name='EtlListingsQuarterly',
        ),
        migrations.RenameField(
            model_name='etllistingsquarterly',
            old_name='quaterofyear',
            new_name='quarterofyear',
        ),
    ]
