# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-10 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svrea_etl', '0015_etlhistogramfavourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='etllistingsdaily',
            name='sold_daysbeforesold_avg',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
