# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-10 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svrea_etl', '0016_etllistingsdaily_sold_daysbeforesold_avg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etllistingsdaily',
            name='sold_daysbeforesold_avg',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
