# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-10 16:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svrea_etl', '0017_auto_20170810_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etllistingsdaily',
            name='sold_daysbeforesold_avg',
        ),
    ]
