# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-17 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svrea_etl', '0021_etllistingsdaily_sold_propertyage_avg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etllistingsdaily',
            name='sold_propertyage_avg',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
