# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-17 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svrea_etl', '0022_auto_20170817_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='etllistingsmonthly',
            name='sold_propertyage_avg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etllistingsquarterly',
            name='sold_propertyage_avg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etllistingsweekly',
            name='sold_propertyage_avg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etllistingsyearly',
            name='sold_propertyage_avg',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
