# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-22 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svrea_etl', '0023_auto_20170817_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='etllistingsdaily',
            name='property_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
