# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-22 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svrea_etl', '0024_etllistingsdaily_property_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='etllistingsmonthly',
            name='property_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='etllistingsquarterly',
            name='property_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='etllistingsweekly',
            name='property_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='etllistingsyearly',
            name='property_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
