# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField(auto_now=True)),
                ('user_name', models.CharField(default='None', max_length=50)),
                ('config', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('comment', models.CharField(max_length=500)),
            ],
            options={
                'permissions': (('can_run_script', 'Can run script'), ('can_see_history', 'Can See History')),
            },
        ),
    ]
