# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 20:34
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('addressid', models.AutoField(primary_key=True, serialize=False)),
                ('house', models.CharField(max_length=10)),
                ('street', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=50)),
                ('municipality', models.CharField(max_length=50)),
                ('county', models.CharField(max_length=50)),
                ('areaname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Aux',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField(auto_now=True)),
                ('user_name', models.CharField(default='None', max_length=50)),
                ('config', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('comment', models.CharField(default='None', max_length=500)),
            ],
            options={
                'permissions': (('can_run_script', 'Can run script'), ('can_see_history', 'Can See History')),
            },
        ),
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('booliid', models.IntegerField(primary_key=True, serialize=False)),
                ('datepublished', models.DateTimeField(db_index=True, default=None)),
                ('latitude', models.DecimalField(decimal_places=8, default=None, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, default=None, max_digits=10)),
                ('constructionyear', models.IntegerField(default=None)),
                ('rent', models.IntegerField(default=None)),
                ('url', models.CharField(default=None, max_length=250)),
                ('rooms', models.CharField(default=None, max_length=10)),
                ('propertytype', models.CharField(default=None, max_length=50)),
                ('plotarea', models.DecimalField(decimal_places=1, default=None, max_digits=5)),
                ('additionalarea', models.DecimalField(decimal_places=1, default=None, max_digits=5)),
                ('livingarea', models.DecimalField(decimal_places=1, default=None, max_digits=5)),
                ('floor', models.CharField(default=None, max_length=10)),
                ('isnewconstruction', models.BooleanField(default=None)),
                ('datesold', models.DateTimeField(default=None)),
                ('isactive', models.BooleanField(db_index=True, default=None)),
                ('dateinactive', models.DateTimeField(default=None)),
                ('latestprice', models.IntegerField(default=None)),
                ('addressid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svrea_script.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(max_length=20)),
                ('entry', models.CharField(default='None', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Pricehistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('ifsoldprice', models.BooleanField()),
                ('booliid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svrea_script.Listings')),
            ],
        ),
        migrations.CreateModel(
            name='Rawdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded', models.DateTimeField(auto_now=True)),
                ('uploaded', models.BooleanField(default=False)),
                ('type', models.CharField(max_length=50)),
                ('areacode', models.IntegerField()),
                ('rawdata', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('sourceid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('sourcetype', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='listings',
            name='sourceid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svrea_script.Source'),
        ),
        migrations.AlterIndexTogether(
            name='address',
            index_together=set([('street', 'city', 'municipality', 'county')]),
        ),
    ]
