# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 10:03
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('addressid', models.AutoField(primary_key=True, serialize=False)),
                ('house', models.CharField(blank=True, max_length=10, null=True)),
                ('street', models.CharField(blank=True, max_length=250, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('municipality', models.CharField(blank=True, max_length=50, null=True)),
                ('county', models.CharField(blank=True, max_length=50, null=True)),
                ('areaname', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'svrea_data"."address',
            },
        ),
        migrations.CreateModel(
            name='Aux',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'svrea_data"."aux',
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField(auto_now=True)),
                ('user_name', models.CharField(default='None', max_length=50)),
                ('config', django.contrib.postgres.fields.jsonb.JSONField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('comment', models.CharField(default='None', max_length=500)),
            ],
            options={
                'db_table': 'svrea_data.info',
                'permissions': (('can_run_script', 'Can Run Script'), ('can_see_info', 'Can See Info'), ('can_see_script_logs', 'Can See Script Logs'), ('can_see_data', 'Can See Data')),
            },
        ),
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('booliid', models.IntegerField(primary_key=True, serialize=False)),
                ('datepublished', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('constructionyear', models.IntegerField(blank=True, null=True)),
                ('rent', models.IntegerField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=250, null=True)),
                ('rooms', models.CharField(blank=True, max_length=10, null=True)),
                ('propertytype', models.CharField(blank=True, max_length=50, null=True)),
                ('plotarea', models.IntegerField(blank=True, null=True)),
                ('additionalarea', models.IntegerField(blank=True, null=True)),
                ('livingarea', models.IntegerField(blank=True, null=True)),
                ('floor', models.CharField(blank=True, max_length=10, null=True)),
                ('isnewconstruction', models.NullBooleanField()),
                ('datesold', models.DateTimeField(blank=True, null=True)),
                ('isactive', models.NullBooleanField(db_index=True)),
                ('dateinactive', models.DateTimeField(blank=True, null=True)),
                ('latestprice', models.IntegerField(blank=True, null=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='svrea_script.Address')),
            ],
            options={
                'db_table': 'svrea_data"."listings',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(max_length=20)),
                ('entry', models.CharField(default='None', max_length=500)),
            ],
            options={
                'db_table': 'svrea_data"."log',
            },
        ),
        migrations.CreateModel(
            name='Pricehistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('issoldprice', models.BooleanField()),
                ('booliid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svrea_script.Listings')),
            ],
            options={
                'db_table': 'svrea_data"."pricehistory',
            },
        ),
        migrations.CreateModel(
            name='Rawdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded', models.DateTimeField(blank=True, null=True)),
                ('uploaded', models.DateTimeField(blank=True, null=True)),
                ('isuploaded', models.BooleanField(default=False)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('areacode', models.IntegerField(blank=True, null=True)),
                ('rawdata', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'db_table': 'svrea_data"."rawdata',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('sourceid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('sourcetype', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'svrea_data"."source',
            },
        ),
        migrations.AddField(
            model_name='listings',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='svrea_script.Source'),
        ),
        migrations.AlterIndexTogether(
            name='address',
            index_together=set([('street', 'city', 'municipality', 'county')]),
        ),
    ]
