# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('svrea_script', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='addressid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='svrea_script.Address'),
        ),
        migrations.AlterField(
            model_name='listings',
            name='latitude',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='listings',
            name='sourceid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='svrea_script.Source'),
        ),
    ]
