# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 10:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svrea_script', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricehistory',
            old_name='ifsoldprice',
            new_name='issoldprice',
        ),
    ]
