# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 13:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svrea_script', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Svrea_script_info',
            new_name='Info',
        ),
    ]
