# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svrea_script', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(max_length=20)),
                ('entry', models.CharField(default='None', max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='info',
            name='comment',
            field=models.CharField(default='None', max_length=500),
        ),
    ]
