# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-30 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svrea_script', '0002_auto_20170417_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.CharField(default='Sweden', max_length=50),
        ),
    ]
