# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svrea_script', '0002_auto_20170227_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='additionalarea',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='listings',
            name='livingarea',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='listings',
            name='plotarea',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
    ]
