# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svrea_script', '0002_auto_20170214_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='additionalarea',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='listings',
            name='constructionyear',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listings',
            name='dateinactive',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listings',
            name='datepublished',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='listings',
            name='datesold',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listings',
            name='floor',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='listings',
            name='isactive',
            field=models.NullBooleanField(db_index=True),
        ),
        migrations.AlterField(
            model_name='listings',
            name='isnewconstruction',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='listings',
            name='latestprice',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listings',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='listings',
            name='livingarea',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='listings',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='listings',
            name='plotarea',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='listings',
            name='propertytype',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='listings',
            name='rent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listings',
            name='rooms',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='listings',
            name='url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
