# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 15:57
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svrea_script', '0002_auto_20170204_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rawdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=50)),
                ('areacode', models.IntegerField()),
                ('rawdata', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.RenameModel(
            old_name='ScriptLog',
            new_name='Log',
        ),
    ]
