# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 14:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svrea_script', '0002_auto_20170129_1337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'permissions': (('can_run_script', 'Can run script'), ('can_see_history', 'Can See History'))},
        ),
    ]
