# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svrea_script', '0003_auto_20170129_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='script',
            new_name='config',
        ),
        migrations.RenameField(
            model_name='info',
            old_name='date_started',
            new_name='started',
        ),
        migrations.AddField(
            model_name='info',
            name='user_name',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
