# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svrea_script', '0003_auto_20170227_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='additionalarea',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listings',
            name='livingarea',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listings',
            name='plotarea',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
