# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svrea_script', '0003_auto_20170205_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aux',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
            ],
        ),
    ]
