# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-08 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svrea_script', '0004_auto_20170709_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='county',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='municipality',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
