# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('svrea_script', '0004_aux'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('addressid', models.AutoField(primary_key=True, serialize=False)),
                ('house', models.CharField(max_length=10)),
                ('street', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=50)),
                ('municipality', models.CharField(max_length=50)),
                ('county', models.CharField(max_length=50)),
                ('areaname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('booliid', models.IntegerField(primary_key=True, serialize=False)),
                ('datepublished', models.DateTimeField(db_index=True)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('constructionyear', models.IntegerField()),
                ('rent', models.IntegerField()),
                ('url', models.CharField(max_length=250)),
                ('rooms', models.CharField(max_length=10)),
                ('propertytype', models.CharField(max_length=50)),
                ('plotarea', models.DecimalField(decimal_places=1, max_digits=5)),
                ('additionalarea', models.DecimalField(decimal_places=1, max_digits=5)),
                ('livingarea', models.DecimalField(decimal_places=1, max_digits=5)),
                ('floor', models.CharField(max_length=10)),
                ('isnewconstruction', models.BooleanField()),
                ('datesold', models.DateTimeField()),
                ('isactive', models.BooleanField(db_index=True)),
                ('dateinactive', models.DateTimeField()),
                ('latestprice', models.IntegerField()),
                ('addressid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svrea_script.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Pricehistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('ifsoldprice', models.BooleanField()),
                ('booliid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svrea_script.Listings')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('sourceid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('sourcetype', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='listings',
            name='sourceid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svrea_script.Source'),
        ),
        migrations.AlterIndexTogether(
            name='address',
            index_together=set([('street', 'city', 'municipality', 'county')]),
        ),
    ]
