# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 14:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svrea_script', '0004_auto_20170226_1133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listings',
            old_name='addressid',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='listings',
            old_name='sourceid',
            new_name='source',
        ),
    ]
