# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svrea_script', '0004_auto_20170228_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricehistory',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
