# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 12:28
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svrea_script', '0005_auto_20170228_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='config',
            field=django.contrib.postgres.fields.jsonb.JSONField(max_length=200),
        ),
    ]
