# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-28 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svrea_script', '0006_globalvars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='entry',
            field=models.CharField(default='None', max_length=2000),
        ),
    ]
