# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svrea_script', '0006_rawdata_uploaded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='addressid',
        ),
        migrations.AddField(
            model_name='address',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listings',
            name='additionalarea',
            field=models.DecimalField(decimal_places=1, default=None, max_digits=5),
        ),
        migrations.AlterField(
            model_name='listings',
            name='constructionyear',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='listings',
            name='dateinactive',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='listings',
            name='datepublished',
            field=models.DateTimeField(db_index=True, default=None),
        ),
        migrations.AlterField(
            model_name='listings',
            name='datesold',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='listings',
            name='floor',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='listings',
            name='isactive',
            field=models.BooleanField(db_index=True, default=None),
        ),
        migrations.AlterField(
            model_name='listings',
            name='isnewconstruction',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='listings',
            name='latestprice',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='listings',
            name='latitude',
            field=models.DecimalField(decimal_places=8, default=None, max_digits=10),
        ),
        migrations.AlterField(
            model_name='listings',
            name='livingarea',
            field=models.DecimalField(decimal_places=1, default=None, max_digits=5),
        ),
        migrations.AlterField(
            model_name='listings',
            name='longitude',
            field=models.DecimalField(decimal_places=8, default=None, max_digits=10),
        ),
        migrations.AlterField(
            model_name='listings',
            name='plotarea',
            field=models.DecimalField(decimal_places=1, default=None, max_digits=5),
        ),
        migrations.AlterField(
            model_name='listings',
            name='propertytype',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='listings',
            name='rent',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='listings',
            name='rooms',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='listings',
            name='url',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
