# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 20:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svrea_script', '0006_auto_20170305_1228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'permissions': (('can_run_script', 'Can run script'), ('can_see_history', 'Can See History'), ('can_see_script_logs', 'Can See Script Logs'))},
        ),
    ]
