# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 11:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svrea_script', '0007_auto_20170305_2001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'permissions': (('can_run_script', 'Can run script'), ('can_see_info', 'Can See Info'), ('can_see_script_logs', 'Can See Script Logs'))},
        ),
    ]
