# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svrea_script', '0009_auto_20170312_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdata',
            name='isuploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='areacode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='downloaded',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='uploaded',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
